# Generated by Django 4.2.6 on 2024-03-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedding_store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
